### ISSUE TITLE
Broken score tracking

### ISSUE THREAD

**Issue by Ericzklm** [180D-FW-2021/Team3#13]
As a result of switching the shooting mechanism from a raycast to spawning a bullet, the code that keeps track of balloons popped and shot accuracy was removed, so the score tracking isnt working properly. shotsHit and shotsTaken in the shooter game object should be updated like the score is.

![image](https://user-images.githubusercontent.com/52121058/142979597-72038f9d-aad8-49fd-aaff-90356e313ce1.png)

**Comment by kevinwiranata** [comment]
Reminder:
- Need to add ```ShooterInstance.shotsHit += 1;``` in ```bullet.cs``` switch statement
